In [2]:
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons

In [3]:
X, y = make_moons(n_samples=1000, noise=0.05)

In [4]:
dbscan = DBSCAN(eps=0.05, min_samples=5)

In [5]:
dbscan.fit(X)

DBSCAN(algorithm='auto', eps=0.05, leaf_size=30, metric='euclidean',
    metric_params=None, min_samples=5, n_jobs=None, p=None)

In [6]:
dbscan.labels_

array([-1,  0,  1,  1,  1,  0,  0,  2,  1,  1,  3,  1,  0,  0,  3,  1,  0,
        1,  1,  1,  0,  1,  1, -1,  3,  4,  4,  3,  1,  1,  1,  1,  0,  1,
        1,  0,  3,  1,  2,  0,  0,  0,  1,  2,  1,  0,  3,  1,  0,  1,  1,
        3,  0,  1,  1, -1,  0,  0,  0, -1,  2,  3,  3,  4,  0,  0,  0,  1,
        1,  0,  0,  1,  0, -1,  1,  3,  4,  3,  3,  5,  3, -1,  0,  0,  1,
        0,  1,  0,  0,  0,  5,  3,  0,  0,  0,  1,  0,  1,  2,  4,  0,  1,
        3,  1, -1,  4,  1,  4,  1,  0,  0,  0,  1,  1,  6,  1,  1,  1,  0,
        5,  6,  0,  2,  2,  1,  4,  0,  4,  0,  0,  1,  1,  5,  3,  1,  0,
        3, -1,  0,  1,  2,  0,  0,  1,  0,  4,  3,  4,  3,  1,  1,  1,  4,
        1,  0,  0,  0,  0,  1,  0,  1,  1,  1,  0,  1,  1,  0,  2,  0,  0,
        0,  4,  1,  0,  1,  0,  0,  1,  1,  0,  0,  3,  1,  0,  3, -1,  1,
        1,  0,  2,  1,  4,  1,  0,  0,  0,  0,  1,  0,  2,  0, -1, -1,  0,
       -1,  3,  1,  1,  1,  2,  1,  1,  0,  1,  1,  0, -1,  5,  1,  1,  0,
        1,  1, -1,  3,  2

In [7]:
dbscan.core_sample_indices_

array([  1,   2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  24,  25,  26,  28,  29,
        30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  50,  51,  53,  54,  56,  58,  60,
        61,  62,  65,  66,  67,  68,  69,  70,  71,  72,  74,  75,  78,
        79,  80,  82,  83,  84,  85,  86,  87,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 106, 107, 108, 109,
       110, 111, 112, 113, 115, 116, 117, 118, 120, 121, 122, 123, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 136, 138, 139, 140, 141,
       142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 162, 163, 165, 166, 168, 169, 170,
       171, 172, 173, 174, 176, 177, 178, 179, 181, 182, 183, 184, 186,
       187, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
       203, 206, 207, 209, 210, 211, 212, 213, 214, 215, 217, 21

In [8]:
dbscan.components_

array([[-0.01172145,  0.19391854],
       [-0.00728695,  0.98488963],
       [-0.87360236,  0.49453997],
       ...,
       [ 1.76345578, -0.11715224],
       [-1.01544777,  0.24357133],
       [ 1.93381253,  0.13252197]])